name: Build & Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [ "feat/cicd-github-actions" ]   # later change to main
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read


jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set vars
        run: |
          echo "ACR_NAME=${{ vars.ACR_NAME }}" >> $GITHUB_ENV
          echo "ACR_LOGIN_SERVER=${{ vars.ACR_LOGIN_SERVER }}" >> $GITHUB_ENV
          echo "RG=${{ vars.WORKLOAD_RG }}" >> $GITHUB_ENV
          echo "CA_NAME=${{ vars.CA_NAME }}" >> $GITHUB_ENV
          echo "IMAGE=${{ vars.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: ACR login
        run: |
          az acr login --name ${{ vars.ACR_NAME }}
    

      - name: Build and push (amd64)
        run: |
          docker buildx create --use --name builder || docker buildx use builder
          echo "IMAGE=${IMAGE}"
          echo "TAG=${TAG}"

          docker buildx build \
            --platform linux/amd64 \
            -t "${IMAGE}:${TAG}" \
            -t "${IMAGE}:latest" \
            --push \
            ./app

      - name: Deploy to Azure Container App
        run: |
          az extension add --name containerapp --upgrade
          az containerapp update \
            --resource-group "${RG}" \
            --name "${CA_NAME}" \
            --image "${IMAGE}:${TAG}"

      - name: Smoke test /health
        run: |
          FQDN=$(az containerapp show -g ${RG} -n ${CA_NAME} --query properties.configuration.ingress.fqdn -o tsv)
          echo "FQDN=${FQDN}"
          curl -i --max-time 20 "https://${FQDN}/health"